---
title: "Cluster With 4 demographic factors"
author: "Li Liu"
date: "12/11/2019"
output: html_notebook
---


## Data preparatio
```{r prep}
library(tidyverse)
library(here)
library(cluster)
library(FactoMineR)
library(factoextra)
library(NbClust)
library(dbscan)
library(cowplot)
library(skimr)
library(ggcorrplot)
library(missMDA)
library(cluster)
library(data.table)

setwd('C:/Users/lliu9/Desktop/UML_Project/unsupervised-dating/Data')
data <- read_csv("final_okcupid.csv")
data_sample <- sample_n(data, 2000)

demo <- data_sample[c('fit', 'edu', 'height_group', 'race_ethnicity')]

gower_demo <- demo %>%
              mutate_all(factor) %>% 
              daisy(metric = "gower")
```

## Kmeans model
K means with 4 variables:Educational level, weight, height (all ordinal), and race (categorical) 

```{r Kmeans}
set.seed(123)

kmeans <- kmeans(gower_demo, 
                 centers  = 3,
                 nstart = 15)

```

## save text data with cluster label for topic modeling 
```{r}
text <- data_sample[c('clean_text')]
text$kmeanscluster = as.factor(kmeans$cluster)
write_csv(text, 'essay0.csv')
```



## Examination
```{r Examination}
data_sample$kmeanscluster = as.factor(kmeans$cluster)

# Inspect the kmeans object
str(kmeans)
```


## Visualization
```{r Visualization}
jpeg('kmeans3.jpeg')
fviz_cluster(kmeans, gower_demo)
dev.off()
```



## Validation

```{r validation}
library(fpc)
#Calinski Harabasz index
clustering.ch <- kmeansruns(gower_demo,krange = 1:5,criterion = "ch")
#average silhouette width 
clustering.asw <- kmeansruns(gower_demo,krange = 1:5,criterion = "asw")

critframe <- data.frame(k=1:10, ch=scale(clustering.ch$crit),
             asw=scale(clustering.asw$crit))

critframe <- melt(critframe, id.vars=c("k"), variable.name="measure",
             value.name="score")

ggplot(critframe, aes(x=k, y=score, color=measure)) +
        geom_point(aes(shape=measure)) + geom_line(aes(linetype=measure)) +
scale_x_continuous(breaks=1:10, labels=1:10)
summary(clustering.ch)


```

