---
title: "Exploratory Data Analysis"
author: "Adam Shelton"
date: "10/29/2019"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(here)
library(knitr)
library(kableExtra)
library(corrplot)
library(GGally)
library(treemapify)
library(lubridate)
library(ggmap)

knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10, dpi = 300)

source(here::here("Data", "get_data.R"))
source(here::here("api_keys.R"))

register_google(gmaps_key)

fix_nas = function(data_set, na_strs) {
  library(tidyverse)
  for (var in names(data_set)) {
    data_set[[var]][data_set[[var]] %in% na_strs] = NA
  }
  return(data_set)
}

collapse_to_other = function(variable, n_categories, ...) {
  library(tidyverse)
  if (length(unique(variable)) > n_categories) {
    var_table = variable %>% table() %>% as_tibble() %>% arrange(-n)
    other_cats = var_table$.[n_categories:length(var_table$.)]
    variable = variable %>% as.character()
    variable[variable %in% other_cats] = "Other"
    variable[str_to_lower(variable) == "other"] = "Other"
  }
  return(variable)
}
```

## Previously Processed Dataset

### Data Preparation
```{r data-import}
raw_data = read_csv(here::here("Data", "compressed_okcupid.csv")) 

collapse_ethnicity =  Vectorize(function(x) {
  if (is.na(x)) {
    return(x)
  }
  if (str_detect(x, ",")) {
    if (str_detect(str_to_lower(x), "white")) {
      return("multi / white")
    }
    return("multi")
  }
  return(str_to_lower(x))
})
cleaned_data = raw_data %>% fix_nas(c("unknown")) %>% mutate(race_ethnicity = collapse_ethnicity(ethnicity), X1 = NULL) %>% mutate_if((function(x) length(unique(x)) < 20), factor)
```

### Descriptive Statistics
```{r desc-stats}
data_descriptives = cleaned_data %>% skim_to_list() 
data_descriptives[[1]] %>% kable(caption = "Text Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
data_descriptives[[2]] %>% kable(caption = "Categorical Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
data_descriptives[[3]] %>% kable(caption = "Continuous Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
```

### Visualizations

#### Continuous Variables
```{r num-viz}
cleaned_data %>% select_if(is.numeric) %>% ggpairs(progress = FALSE) + theme(axis.text.x = element_text(angle = 20, hjust = 1))
```

#### Categorical Variables
```{r factors-viz}
cleaned_data %>% select_if(is.factor) %>% pivot_longer(dplyr::everything()) %>% table() %>% as_tibble() %>% ggplot(aes(area = n, fill = value, label = value)) + geom_treemap() + geom_treemap_text(color = "white", place = "centre", grow = TRUE) + facet_wrap(~ name) + theme(legend.position = "none")

cleaned_data %>% select_if(is.factor) %>% na.omit() %>% mutate_all(collapse_to_other, n_categories = 4) %>% ggpairs(progress = FALSE) + theme(axis.text.x = element_text(angle = 20, hjust = 1))
```

## Full Dataset

### Data Preparation
```{r full-data-load, cache=TRUE, message=FALSE}
full_raw_data = read_csv(here::here("Data", "full_ok_cupid.csv")) 
```

```{r full-data-functs, cache=TRUE, message=FALSE}
get_first_word = Vectorize(function(x){
  if (is.na(x)) {
    return(x)
  }
  str_split(x, " ")[[1]][1]
})

can_char_be_factor = function(x, n = 20) {
  if (is.character(x)) {
    return(length(unique(x)) < n)
  }
  return(FALSE)
}

get_diet = Vectorize(function(x, importance = FALSE) {
  split_char = str_split(x, " ")[[1]]
  if (length(split_char) == 1) {
    if (importance) {
      return(NA)
    }
    return(x)
  }
  if (importance) {
    return(split_char[1])
  }
  split_char[2]
})

other_importance = Vectorize(function(x) {
  if (is.na(x)) {
    return(x)
  }
  if (str_detect(x, "and")) {
     and_split = str_split(x, "and")[[1]]
     return(str_trim(and_split[2]))
  }
  if (str_detect(x, "but")) {
     but_split = str_split(x, "but")[[1]]
     return(str_trim(but_split[2]))
  }
  return(NA)
})

get_pets = Vectorize(function(x, pet_type) {
  if (is.na(x)) {
    return(x)
  }
  if (str_detect(x, paste("has", pet_type))) {
    return(paste("has", pet_type))
  }
  if (str_detect(x, paste("dislikes", pet_type))) {
    return(paste("dislikes", pet_type))
  }
  if (str_detect(x, paste("likes", pet_type))) {
    return(paste("likes", pet_type))
  }
  return(NA)
})

get_kids = Vectorize(function(x, wants = FALSE) {
  if (is.na(x)) {
    return(x)
  }
  if (wants) {
    if (str_detect(x, "doesn't want more")) {
      return("doesn't want more kids")
    }
    if (str_detect(x, "doesn't want")) {
      return("doesn't want kids")
    }
    if (str_detect(x, "might want")) {
      return("might want kids")
    }
    if (str_detect(x, "wants more")) {
      return("wants more kids")
    }
        if (str_detect(x, "wants")) {
      return("wants kids")
    }
  } else {
    if (str_detect(x, "doesn't have")) {
      return("doesn't have kids")
    }
    if (str_detect(x, "has kids")) {
      return("has kids")
    }
    if (str_detect(x, "has a kid")) {
      return("has a kid")
    }
  }
  return(NA)
})
```

```{r full-loc, cache=TRUE, message=FALSE}
location_data = full_raw_data %>% select(location) %>% unique() %>% bind_cols(geocode(unlist(.)))
san_fran_loc = c(-122.4194155, 37.77493)
all_locations = location_data %>% select(-location) %>% as.matrix()
location_data$distance = geosphere::distGeo(san_fran_loc, all_locations) * 0.000621371 # calculates distance between SF and all other locations and converts from meters to mils
location_data$visiting = location_data$distance > 25 # users are designated as "visiting" if the specified location on their profile is a certain distance from SF
```

```{r full-cleaning, cache=TRUE, message=FALSE}
full_cleaned_data = full_raw_data %>% 
  mutate_if(is.character, str_replace_all, pattern = "&rsquo;", replacement = "'") %>% 
  mutate(religion_raw = religion, religion_import = other_importance(religion), religion = get_first_word(religion), 
         sign_raw = sign, sign_import = other_importance(sign), sign = get_first_word(sign), 
         diet_raw = diet, diet_import = get_diet(diet, TRUE), diet = get_diet(diet),
         dogs = get_pets(pets, "dogs"), cats = get_pets(pets, "cats"), pets_raw = pets, pets = NULL,
         kids = get_kids(offspring), kids_import = get_kids(offspring, TRUE), kids_raw = offspring, offspring = NULL,
         speaks_en = str_detect(speaks, "english"), multi_ling = str_detect(speaks, ","), 
         ethnicity_raw = ethnicity, ethnicity = collapse_ethnicity(ethnicity),
         last_online_raw = last_online, last_online = ymd_hm(last_online), 
         year_last_online = year(last_online), month_last_online = month(last_online), day_last_online = day(last_online),
         time_since_online = as.period(max(last_online) - last_online), days_since_online = period_to_seconds(time_since_online) %>%  (function(x) x / 86400)) %>% 
  mutate_if(can_char_be_factor, factor) %>% left_join(location_data)

saveRDS(full_cleaned_data, here::here("Data", "full_ok_cupid_cleaned.rds"))
write_csv(full_cleaned_data, here::here("Data", "full_ok_cupid_cleaned.csv"))
```

### Descriptive Statistics
```{r full-desc-stats}
full_data_descriptives = full_cleaned_data %>% skim_to_list() 
full_data_descriptives[[1]] %>% kable(caption = "Text Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
full_data_descriptives[[2]] %>% kable(caption = "Categorical Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
full_data_descriptives[[4]] %>% kable(caption = "Dummy Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
full_data_descriptives[[5]] %>% kable(caption = "Continuous Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
full_data_descriptives[[6]] %>% kable(caption = "Date-time Variables") %>% kable_styling(bootstrap_options = c("striped", "condensed", "responsive"))
```

### Visualizations

#### Continuous Variables
```{r full-num-viz, warning=FALSE}
full_cleaned_data %>% select_if(is.numeric) %>% select(-time_since_online) %>% ggpairs(progress = FALSE) + theme(axis.text.x = element_text(angle = 20, hjust = 1))
```

#### Categorical Variables
```{r full-factors-viz, warning=FALSE}
is_categorical = function(x) {
  is.factor(x) | is.logical(x)
}

full_cleaned_data %>% select_if(is_categorical) %>% select(-ends_with("raw")) %>% mutate_all(factor) %>% pivot_longer(dplyr::everything()) %>% table() %>% as_tibble() %>% ggplot(aes(area = n, fill = value, label = value)) + geom_treemap() + geom_treemap_text(color = "white", place = "centre", grow = TRUE) + facet_wrap(~ name) + theme(legend.position = "none")

full_cleaned_data %>% select_if(is_categorical) %>% select(-ends_with("raw")) %>% mutate_all(factor) %>% mutate_all(collapse_to_other, n_categories = 4) %>% pivot_longer(dplyr::everything()) %>% na.omit() %>% ggplot(aes(x = value)) + geom_bar() + scale_x_discrete(labels = abbreviate) + facet_wrap(~ name, scales = "free_x") + theme(axis.text.x = element_text(angle = 20, hjust = 1))
```